### ISSUE TITLE
Support for intelli-j IDE

### ISSUE THREAD

**Issue by dpnkrg** [Foso/HtmlToComposeWebConverter#4]
**Describe the bug**
I am unable to install plugin in intellij idea.

**Expected behavior**
Plugin should work.

**Screenshots**

![image](https://user-images.githubusercontent.com/10338350/177155599-1ffd5b17-be30-4cc7-84e7-fc41cba33591.png)

```
IntelliJ IDEA 2022.1.2 (Ultimate Edition)

Build #IU-221.5787.30, built on June 1, 2022

Licensed to XXXXX- Gupta
Subscription is active until July 22, 2022.
For educational use only.

Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

```

**Comment by Foso** [comment]
Hey @dpnkrg , thank you for reporting this. I just released v1.0.6 that should be working again. The update is in review in the Plugin Marketplace, but you can get the zip from the GitHub Released Page
